export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

export const OBTENER_REPOS = 'OBTENER_REPOS';
export const AGREGAR_FAVORITO = 'AGREGAR_FAVORITO';
export const ELIMINAR_FAVORITO = 'ELIMINAR_FAVORITO';